name: Deploy frontend

on:
  push:
    branches:
      - main
    paths:
      - ../frontend/**
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@4
      - name: Set up node
        uses: actions/setup-node@4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Generate API
        run: npm run generate-api
      - name: Build
        run: npm run build
        env:
          VITE_DIGEST_TEMPLATE_EDIT_URL: ${{ vars.DIGEST_TEMPLATE_EDIT_URL }}
          VITE_PARSING_SITES_TABLE_URL: ${{ vars.PARSING_SITES_TABLE_URL }}
          VITE_EXTRACTED_NEWS_TABLE_URL: ${{ vars.EXTRACTED_NEWS_TABLE_URL }}
          VITE_RANKED_NEWS_TABLE_URL: ${{ vars.RANKED_NEWS_TABLE_URL }}
          VITE_SUMMARIZED_NEWS_TABLE_URL: ${{ vars.SUMMARIZED_NEWS_TABLE_URL }}
          VITE_RANKING_LANG_SMITH_URL: ${{ vars.RANKING_LANG_SMITH_URL }}
          VITE_PARSING_LANG_SMITH_URL: ${{ vars.PARSING_LANG_SMITH_URL }}
          VITE_SUMMARIZING_LANG_SMITH_URL: ${{ vars.SUMMARIZING_LANG_SMITH_URL }}
      - name: Deploy
        uses: nekitcorp/yandex-storage-website-action@v1
        with:
          accessKeyId: ${{ secrets.FRONTEND_DEPLOY_ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.FRONTEND_DEPLOY_SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.FRONTEND_BUCKET }}
          path: "./dist"
          clear: true
