name: Deploy frontend

on:
  push:
    branches:
      - main
    paths:
      - ../frontend/**
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@4
      - name: Set up node
        uses: actions/setup-node@4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install
        run: npm install
      - name: Generate API
        run: npm run generate-api
      - name: Build
        run: npm run build
        env:
          VITE_LANG_SMITH_URL: "https://smith.langchain.com/hub/mlenparrot/nlmk_grade"
          VITE_GOOGLE_SHEETS_URL: "https://docs.google.com/spreadsheets/d/1Fdfk6PJuE0zAVQpaH6dv3b7SkNByn8AAdzrEDL3EUUQ/edit#gid=1958678976"
          VITE_DIGEST_TEMPLATE_EDIT_URL: "https://www.overleaf.com/read/vyqdnhjfjnwh#4c8ad1"
      - name: Deploy
        uses: nekitcorp/yandex-storage-website-action@v1
        with:
          accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.SECRET_ACCESS_KEY }}
          bucket: ${{ secrets.BUCKET }}
          path: "./dist"
          clear: true
